// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egcdzicxyrbwnjfiiuqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnY2R6aWN4eXJid25qZmlpdXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTgwODUsImV4cCI6MjA3MDAzNDA4NX0.RiuY2ptHkR_kg38TiNpwoQf6j_sdSHyx4q1zagb90Qw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});